name: $(Date:yyyyMMdd)$(Rev:.r)
schedules:
  - cron: "0 */6 * * *"
    displayName: Regular sync every 6 hours
    always: true
trigger:
  branches:
    include: [master, latest]

variables:
  branches: [master, latest]

jobs:
- job: 
  workspace: 
    clean: resources
  steps:
  - script: echo First step! && echo "$branches"