name: $(Date:yyyyMMdd)$(Rev:.r)
trigger:
  branches:
    include: [master, latest]

jobs:
- job: 
  variables:
    source_branch: master
    target_endpoints: >
      git@github.com:test-repo-tih/test-sync.git!master
      git@github.com:test-repo-tih/test-sync.git!test
  workspace: 
    clean: resources
  steps:
  - script: |
      echo "Hello World!"
      echo "source_branch $(source_branch)"
      echo "target_endpoints $(target_endpoints)"
      git branch --no-track -C $(source_branch) origin/$(source_branch)
      for target in $(target_endpoints)
      do
        echo "TARGET $target"
      done
