name: $(Date:yyyyMMdd)$(Rev:.r)
trigger:
  branches:
    include: [master, latest]

jobs:
- job: 
  variables:
    SOURCE_BRANCH: master
    TARGET_ENDPOINTS: >
      git@github.com:test-repo-tih/test-sync.git!master
      git@github.com:test-repo-tih/test-sync.git!test
  workspace: 
    clean: resources
  steps:
  - checkout: self
    clean: resources
    persistCredentials: true
  - script: |
      git config user.email "azuresdkci@microsoft.com"
      git config user.name "azuresdkci"
      git config credential.helper store

      echo https://$(Github-azuresdkci-personalaccesstoken):x-oauth-basic@github.com > ~/.git-credentials

      set -x
      git branch --no-track -f $SOURCE_BRANCH origin/$SOURCE_BRANCH
      set +x

      for TARGET in $TARGET_ENDPOINTS
      do
        TARGET_REPO=`echo $TARGET | cut -d! -f 1 -`
        TARGET_BRANCH=`echo $TARGET | cut -d! -f 2 -`
        echo "TARGET_REPO=$TARGET_REPO"
        echo "TARGET_BRANCH=$TARGET_BRANCH"

        set -x
        git remote remove target
        git remote add target $TARGET_REPO
        git push -f target origin/$SOURCE_BRANCH:$TARGET_BRANCH
        set +x

      done
