name: $(Date:yyyyMMdd)$(Rev:.r)
parameters:
  branches:
    - master
    - latest
trigger:
  branches:
    include: ${{ parameters.branches }}
schedules:
  - cron: "0 */6 * * *"
    displayName: Regular sync every 6 hours
    branches:
      include: ${{ parameters.branches }}
    always: true
variables:
  branches: ${{ parameters.branches }}

jobs:
- job: 
  workspace: 
    clean: resources
  steps:
  - script: echo First step! && echo "$branches"