variables:
  skipComponentGovernanceDetection: true
resources:
  repositories:
    - repository: mirror_template
      type: github
      name: AzureSDKAutomation/repo-mirror-template
      endpoint: Azure
trigger:
  batch: true
  branches:
    include: [master, latest]

jobs:
  - template: .azure-pipelines/job-mirror.yml@mirror_template
    parameters:
      TARGET_ENDPOINTS: >
        https://github.com/test-repo-tih/test-sync.git!master
        https://github.com/test-repo-tih/test-sync.git!test
