variables:
  skipComponentGovernanceDetection: true
resources:
  repositories:
    - repository: mirror_template
      type: github
      name: test-repo-tih/test-mirror-repo-template
trigger:
  branches:
    include: [master, latest]

jobs:
- template: .azure-pipelines/mirror-template.yml@mirror_template
  parameters:
    SOURCE_BRANCH: master
    TARGET_ENDPOINTS: >
      https://github.com/test-repo-tih/test-sync.git!master
      https://github.com/test-repo-tih/test-sync.git!test
