name: $(Date:yyyyMMdd)$(Rev:.r)
trigger:
  branches:
    include: [master, latest]

jobs:
- job: 
  strategy:
    maxParallel: 1
    matrix:
      sync_master_branch:
        source_branch: master
        target_repo: git@github.com:test-repo-tih/test-sync.git
        target_branch: master
  workspace: 
    clean: resources
  steps:
  - script: >
      echo "Hello World!"
      echo "source_branch $(source_branch)"
      echo "target_repo $(target_repo)"
      echo "target_branch $(target_branch)"
  
